// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mormor_Dagnys_Bageri_REST_API.Data;

#nullable disable

namespace Mormor_Dagnys_Bageri_REST_API.Data.Migrations
{
    [DbContext(typeof(MormorDagnysContext))]
    [Migration("20260423133723_CreatedProduct")]
    partial class CreatedProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Commodity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPotalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoicePostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.CustomerContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContacts");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BakedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BestBefore")
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantityPerPack")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.SupplierContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierContacts");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.SupplierPrice", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommodityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerKilo")
                        .HasColumnType("REAL");

                    b.HasKey("SupplierId", "CommodityId");

                    b.HasIndex("CommodityId");

                    b.ToTable("SupplierPrices");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.CustomerContact", b =>
                {
                    b.HasOne("Mormor_Dagnys_Bageri_REST_API.Entities.Customer", "Customer")
                        .WithMany("CustomerContact")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.SupplierContact", b =>
                {
                    b.HasOne("Mormor_Dagnys_Bageri_REST_API.Entities.Supplier", "Supplier")
                        .WithMany("SupplierContact")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.SupplierPrice", b =>
                {
                    b.HasOne("Mormor_Dagnys_Bageri_REST_API.Entities.Commodity", "Commodity")
                        .WithMany("SupplierPrice")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mormor_Dagnys_Bageri_REST_API.Entities.Supplier", "Supplier")
                        .WithMany("SupplierPrice")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Commodity", b =>
                {
                    b.Navigation("SupplierPrice");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Customer", b =>
                {
                    b.Navigation("CustomerContact");
                });

            modelBuilder.Entity("Mormor_Dagnys_Bageri_REST_API.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierContact");

                    b.Navigation("SupplierPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
